services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: bot
    container_name: bot
    networks:
      - bot
    volumes:
      - ./logs:/app/logs:rw
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - OWNER_ID=${OWNER_ID}
      - TEST_CHANNEL_ID=${TEST_CHANNEL_ID}
      - MQTT_BROKER=${MQTT_BROKER}
    restart: always

networks:
  bot:
    driver: bridge
