name: Docker Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t bot .

      - name: Deploy to Docker with secret
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          OWNER_ID: ${{ secrets.OWNER_ID }}
          TEST_CHANNEL_ID: ${{ secrets.TEST_CHANNEL_ID }}
          MQTT_BROKER: ${{ secrets.MQTT_BROKER }}
        run: docker compose -f docker-compose-ci.yml up -d  
        
      - name: Clean up
        run: docker system prune -f
        